spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/authdb
    username: auth_user
    password: auth_pass
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth:9000

