name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-auth:
    name: Build & Test Auth Service
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      
      - name: Build and Test
        working-directory: ./services/auth
        run: mvn -B verify
      
      - name: Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Auth Service Tests
          path: services/auth/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

  build-inventory:
    name: Build & Test Inventory Service
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      
      - name: Build and Test
        working-directory: ./services/inventory
        run: mvn -B verify
      
      - name: Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Inventory Service Tests
          path: services/inventory/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
